server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:spring_security
    username: app_server
    password: Password@123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

redis:
  host: http://127.0.0.1
  port: 6379